app = "tourney-bot"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/python"]

[env]
  PYTHON_VERSION = "3.10.13"
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
