[tool.poetry]
name = "mybot"
version = "0.1.0"
description = ""
authors = ["You <you@example.com>"]

[tool.poetry.dependencies]
python = "3.10.13"
discord.py = "2.3.2"
gspread = "5.8.0"
google-auth = "2.23.0"
Flask = "2.2.5"
gunicorn = "21.2.0"
python-dotenv = "1.0.0"
aiohttp = "3.8.4"
